### GET Version
GET http://localhost:53890/version


### Connect local velez
POST {{perun}}/velez
Content-Type: application/json

{
  "node": {
    "name": "local_dev",
    "addr": "0.0.0.0",
    "port": 53890,
    "security_disabled": true
  }
}

### Create service
POST {{perun}}/service/new
Content-Type: application/json

{
  "image_name": "redsockdev/red-cart:v0.0.17",
  "service_name": "red-cart",
  "replicas": 1
}

### Refresh service
POST {{perun}}/service/red-cart/refresh


### Deploy resources for service
POST {{perun}}/resources/deploy
Content-Type: application/json

{
  "resourceNames": ["red-cart_postgres"]
}

### Deploy service
POST {{perun}}/service/red-cart/deploy
Content-Type: application/json
