app_info:
    name: github.com/Red-Sock/perun
    version: v0.0.1
    startup_duration: 10s
data_sources:
  - resource_name: grpc_matreshka_be
    connection_string: matreshka
    module: github.com/godverv/matreshka-be
  - resource_name: sqlite
    path: ./data/sqlite/Perun.db
server:
    - name: grpc
      port: 50052
environment: []
