app_info:
    name: github.com/Red-Sock/perun
    version: 0.0.1
    startup_duration: 10s
data_sources:
    - resource_name: grpc_matreshka_be
      connection_string: 0.0.0.0:53891
      module: github.com/godverv/matreshka-be
    - resource_name: sqlite
      path: ./data/sqlite/Perun.db
server:
    - name: grpc
      port: 50052
environment:
    - name: dev_mode
      type: bool
      value: true
